# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030577de77f1c611d0d086440b397de0893dd756f3d831ab77ce4820b2b18c5b77efe47d05ef4e1e70bd287505d4e1aebf1511918ca7f0bb98a78ae8f0aafe23

test:
  secret_key_base: bbe6689425f00524698443c270bcb7aff26371455b4185aa7c45a5e7773a512430ef1a874b9f2495ddecb270ccb5dd94593ce6aca8be7dbbf290ba60a4fc4842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
